Fix tidy warnings for r399163 Clang update.
Fix tidy warnings signed char -> int conversions.

/disk/android_trees/aosp-master-plus-llvm/packages/modules/DnsResolver/res_comp.cpp:144:28: error: 'signed char' to 'int' conversion; consider casting to 'unsigned char' first. [cert-str34-c,-warnings-as-errors]
    int pch = PERIOD, ch = *dn++;
                           ^
/disk/android_trees/aosp-master-plus-llvm/packages/modules/DnsResolver/res_comp.cpp:147:19: error: 'signed char' to 'int' conversion; consider casting to 'unsigned char' first. [cert-str34-c,-warnings-as-errors]
        int nch = *dn++;
                  ^
/disk/android_trees/aosp-master-plus-llvm/packages/modules/DnsResolver/res_comp.cpp:168:18: error: 'signed char' to 'int' conversion; consider casting to 'unsigned char' first. [cert-str34-c,-warnings-as-errors]
    while ((ch = *dn++) != '\0')
                 ^

Fix tidy warnings for unused result by casting to void.

/disk/android_trees/aosp-master-plus-llvm/packages/modules/DnsResolver/tests/dns_responder/dns_tls_frontend.cpp:155:5: error: the value returned by this function should be used [bugprone-unused-return-value,-warnings-as-errors]
    connect(backend_socket_.get(), backend_ai_res->ai_addr, backend_ai_res->ai_addrlen);
    ^

Bug: http://b/155835175
Test: m

Change-Id: Iada74f5c50a563012bfd26cee9088a3a72371f56