DnsResolver/DnsTlsSocket - fixes bugprone-unused-return-value warning
Fixes:
  packages/modules/DnsResolver/DnsTlsSocket.cpp:216:5: error: the value returned by this function should be used [bugprone-unused-return-value,-warnings-as-errors]
      bio.release();
      ^
  packages/modules/DnsResolver/DnsTlsSocket.cpp:216:5: note: cast the expression to void to silence this warning

Test: builds
Bug: 153035880
Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I683d13024ae70ff75d1e6d3c78c23a73ab9bc301
Merged-In: I683d13024ae70ff75d1e6d3c78c23a73ab9bc301