Use u32/i32/u64 instead of deprecated type aliases
Trying to get the project to build with cargo is surfacing the following
errors:

error: use of deprecated type alias `libc::uint32_t`: Use u32 instead.
   --> doh/ffi.rs:203:23
    |
203 |     private_dns_mode: uint32_t,
    |                       ^^^^^^^^

error: use of deprecated type alias `libc::int32_t`: Use i32 instead.
   --> doh/ffi.rs:204:6
    |
204 | ) -> int32_t {
    |      ^^^^^^^

error: use of deprecated type alias `libc::uint32_t`: Use u32 instead.
   --> doh/ffi.rs:275:13
    |
275 |     net_id: uint32_t,
    |             ^^^^^^^^

error: use of deprecated type alias `libc::uint64_t`: Use u64 instead.
   --> doh/ffi.rs:280:17
    |
280 |     timeout_ms: uint64_t,
    |                 ^^^^^^^^

error: use of deprecated type alias `libc::uint32_t`: Use u32 instead.
   --> doh/ffi.rs:346:63
    |
346 | pub extern "C" fn doh_net_delete(doh: &DohDispatcher, net_id: uint32_t) {

Test: TH
Flag: EXEMPT mainline
Change-Id: I274961549e8247117d7865cc24d51776bc691551